import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeRegion,requireRegion,deriveRegionStatus,isRoutePlace} from '../src/lib/regions.mjs';
import {distanceKm,pointToRouteKm,nearbyPoints,pointsAlongRoute} from '../src/lib/geo.mjs';
import {collectionMapPoints} from '../src/lib/map-points.mjs';import {relatedForPlace,entriesForRegion} from '../src/lib/content-links.mjs';

const item=(overrides={})=>({title:'X',slug:'x',trip:'georgien-2026',region:'Tbilisi',status:'empfohlen',days:[],related:[],...overrides});
test('known region aliases normalize and unknown values fail loudly',()=>{assert.equal(normalizeRegion('Mtskheta'),'mtskheta-mtianeti');assert.equal(normalizeRegion('Stepantsminda'),'mtskheta-mtianeti');assert.equal(normalizeRegion('Gori'),'shida-kartli');assert.equal(normalizeRegion('Kutaisi'),'imereti');assert.equal(normalizeRegion('Shekvetili'),'guria');assert.equal(normalizeRegion('Batumi'),'adjara');assert.throws(()=>requireRegion('Kaukasus'),/Unbekannter Regionswert/)});
test('region state derives from places first, then dated sights',()=>{assert.equal(deriveRegionStatus('tbilisi',[item({days:['tag-01']})],[]),'visited');assert.equal(deriveRegionStatus('kakheti',[],[item({region:'Kachetien',days:['tag-03']})]),'optional');assert.equal(deriveRegionStatus('samtskhe-javakheti',[item({region:'Samtskhe-Dschawachetien',slug:'vardzia',status:'nicht-auf-route'})],[]),'off-route')});
test('route marker filter keeps dated coordinates and excludes Vardzia',()=>{assert.equal(isRoutePlace(item({days:['tag-01'],coordinates:{lat:1,lon:2}})),true);assert.equal(isRoutePlace(item({slug:'vardzia',status:'nicht-auf-route',coordinates:{lat:1,lon:2}})),false)});
test('map points are generated from collection data and omit missing coordinates',()=>{const result=collectionMapPoints([item({title:'Tbilisi',slug:'tbilisi',coordinates:{lat:41.7,lon:44.8}}),item()], 'place','orte');assert.deepEqual(result.map(x=>x.name),['Tbilisi']);assert.equal(result[0].href,'georgien/orte/tbilisi/')});
test('point-to-route, radius filtering and distance sorting work',()=>{const route=[{lat:0,lon:0},{lat:0,lon:2}],points=[{name:'far',lat:1,lon:1},{name:'near',lat:.01,lon:1}];assert.ok(pointToRouteKm(points[1],route)<2);assert.ok(distanceKm({lat:0,lon:0},{lat:0,lon:1})>100);assert.deepEqual(nearbyPoints(points,{lat:0,lon:1},200).map(x=>x.name),['near','far']);assert.deepEqual(pointsAlongRoute(points,route,10).map(x=>x.name),['near']);assert.deepEqual(nearbyPoints([{name:'none'}],{lat:0,lon:0},10),[])});
test('content relationships cover place to sights, days and region lists',()=>{const place=item({slug:'tbilisi',days:['tag-01']});const sight=item({slug:'museum',days:['tag-01'],related:['tbilisi']});const day=item({slug:'tag-01'});const links=relatedForPlace(place,{sights:[sight],restaurants:[],hotels:[],days:[day]});assert.equal(links.sights[0].slug,'museum');assert.equal(links.days[0].slug,'tag-01');assert.deepEqual(entriesForRegion('tbilisi',[place,sight]).map(x=>x.slug),['tbilisi','museum'])});
